# 16GB RAM | 4GB RAM | 8000 Requests | 20 min | 10 min
[options]
limit_memory_hard = 16777721600
limit_memory_soft = 629145600
limit_request = 8192
limit_time_real = 1200
limit_time_cpu = 600
max_cron_threads = 1
workers = 8

# Database configuration for Odoo
